CREATE TABLE users (
  id IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL
);

CREATE TABLE matches (
  id IDENTITY PRIMARY KEY,
  user1 INT NOT NULL,
  user2 INT NOT NULL,
  user1Hand VARCHAR(10) NOT NULL,
  user2Hand VARCHAR(10) NOT NULL
);
